### ISSUE TITLE
[Feature] - Create Entity-Relationship Diagram

### ISSUE THREAD

**Issue by RespectMathias** [SP-SDU/DeskMotion#17]
### Description

Create a simple, Entity-Relationship Diagram (ERD) for the desk management system. (I prefer non-UML but it is up to you.)

### Motivation

To establish a foundational understanding of the data entities and their relationships within the system, aiding in database design and overall system architecture.

### Proposed Solution

- Sketch or use a tool like draw.io, excalidraw or Lucidchart to design the ERD. 
- Include entities such as Users, Desks, Reservations, MaintenanceSchedules, and any other relevant entities.
- Define attributes and relationships between entities.

### Acceptance Criteria

- [x] Feature is clearly defined.
- [x] ERD includes all relevant entities and relationships.
- [ ] Diagram reviewed and validated by team members.
- [ ] Tests considered (although not applicable for diagrams).

### Additional Info

- Include the diagrams in the project report.
- Review the diagram with the supervisor for feedback.

**Comment by InFamous11** [comment]
![Untitled Diagram drawio](https://github.com/user-attachments/assets/b0ad7572-2eb5-41bf-ab6a-7f23d74b15b4)
