### ISSUE TITLE
[Feature] - Create Class Diagram

### ISSUE THREAD

**Issue by RespectMathias** [SP-SDU/DeskMotion#18]
### Description

Develop a comprehensive Class Diagram representing the system's classes, attributes, methods, and relationships.

### Motivation

To visualize the structure of the system's codebase, facilitating understanding and communication among team members and aiding in future development and maintenance.

### Proposed Solution

- Use a tool like draw.io, Lucidchart, or Visual Paradigm to create the Class Diagram.
- Include all relevant classes, such as User, Desk, Reservation, MaintenanceSchedule, PicoController, etc.
- Show relationships like inheritance, associations, aggregations, and compositions.

### Acceptance Criteria

- [x] Feature is clearly defined.
- [x] Class Diagram includes all relevant classes and relationships.
- [x] Diagram reviewed and approved by team members.
- [x] Tests considered (not applicable for diagrams).

### Additional Info

- Include the diagrams in the project report.
- Use the diagram to verify and possibly refine the existing code structure.

**Comment by Ahmad-Alqadiri** [comment]
Approved
