### ISSUE TITLE
[Feature] - Create Use Case Diagram

### ISSUE THREAD

**Issue by RespectMathias** [SP-SDU/DeskMotion#20]
### Description

Develop a Use Case Diagram illustrating the interactions between users (actors) and the system's functionalities.

### Motivation

To capture the functional requirements of the system from the user's perspective, aiding in ensuring that all user interactions are accounted for.

### Proposed Solution

- Use a diagramming tool to create the Use Case Diagram.
- Identify all actors (e.g., Desk User, Admin, Cleaner, Technician).
- Define use cases such as Login, Register, Control Desk, View Reports, Schedule Maintenance, etc.
- Show relationships like includes and extends where applicable.

### Acceptance Criteria

- [ ] Feature is clearly defined.
- [ ] Use Case Diagram includes all actors and relevant use cases.
- [ ] Diagram reviewed and approved by team members.
- [ ] Tests considered (not applicable for diagrams).

### Additional Info

- Include the diagrams in the project report.
- Use the diagram to verify that all user requirements are being met.

**Comment by Tutejszy777** [comment]
[use case diagram.drawio.pdf](https://github.com/user-attachments/files/17661838/use.case.diagram.drawio.pdf)
