### ISSUE TITLE
[Feature] - Create UI Sketches for All Pages

### ISSUE THREAD

**Issue by RespectMathias** [SP-SDU/DeskMotion#24]
### Description

Design simple UI sketches or wireframes for all planned pages, including:

- Login
- Register
- Account Management
- Dashboard
- Search/List Desks
- Desk Details
- Desk Control
- Maintenance Schedule
- Reports and Analytics
- Admin Panel
- Error Pages (404, 500)

### Motivation

To visualize the user interface and plan the layout and user experience before implementation.

### Proposed Solution

- Sketch or use Figma to create wireframes for each page.
- Focus on simplicity and user-friendly design.
- Include navigation elements and key functionalities for each page.

### Acceptance Criteria

- [ ] Feature is clearly defined.
- [ ] UI sketches for all pages are completed.
- [x] Designs are consistent across all pages.
- [x] Sketches reviewed and approved by team members.
- [x] Tests considered (although not applicable for sketches).

### Additional Info

- Include the UI sketches in the project report under the "Design" section.
- Conduct a peer review of the sketches for feedback.

**Comment by Jagdaw** [comment]
https://www.figma.com/design/yc8l2JRu4OkYfTXQOslf7R/3SemProj_Frame?node-id=0-1&node-type=canvas&t=IyeA0VnFsMr9TJIX-0
